name: status

on: [push, pull_request]

jobs:
  build_on_ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir build; cd build; cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: build
      run: cd build; cmake --build . --target install
    - name: test
      run: ./install/tests
    - name: benchmark
      run: cd install; ./benchmark_test
  coverage_on_ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir build; cd build; cmake -DCMAKE_BUILD_TYPE=COVERAGE ..
    - name: build
      run: cd build; cmake --build . --target install
    - name: test
      run: ./install/tests
    - name: install lcov
      run: sudo apt-get install lcov
    - name: generate coverage info
      run: lcov --capture --directory ./  --output-file temp.info --no-external; lcov --remove temp.info '/usr/include/*' '*tests*'  '*gtests*'  -o coverage.info
    - name: coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: ./coverage.info

  build_on_windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir build; cd build; cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: build
      run: cd build; cmake --build . --target install --config Release
    - name: test
      run: ./install/tests.exe
    - name: benchmark
      run: cd install; ./benchmark_test.exe

  build_on_macOS:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir build; cd build; cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: build
      run: cd build; cmake --build . --target install
    - name: test
      run: ./install/tests
    - name: benchmark
      run: cd install; ./benchmark_test

